In [11]:
# For matrices and arrays
import numpy as np
# For linear algebra functionalities
import scipy.linalg as la
# For floating point operations counting
# To install, pip install python-papi
from pypapi import events, papi_high as high

In [12]:
# Question 1
# Initialzing our matrices here
A = np.array([[130, -3, 0], [-90, 90, 0],
             [-40, -60, 120]])
B = np.array([100, 0, 500])
# Factorizing LU
P, L, U = la.lu(A)
LU, piv = la.lu_factor(A)
# Solving the factorized system
X = la.lu_solve((LU, piv), B)
# Print the matrices
print(L)
print(U)
print(X)

# Part b, c, d
# Calculate inverses of L U

high.start_counters([events.PAPI_FP_OPS, ])
Linv = la.inv(L)
Uinv = la.inv(U)
# Get inverse of A
Ainv = np.matmul(Linv, Uinv)
x1 = high.stop_counters()
print(Ainv)
# Get inverse of A directly
high.start_counters([events.PAPI_FP_OPS, ])
print(la.inv(A))
x = high.stop_counters()
# Get floating point operations

[[ 1.          0.          0.        ]
 [-0.69230769  1.          0.        ]
 [-0.30769231 -0.69291339  1.        ]]
[[130.          -3.           0.        ]
 [  0.          87.92307692   0.        ]
 [  0.           0.         120.        ]]
[0.78740157 0.78740157 4.82283465]
[[0.00769231 0.00026247 0.        ]
 [0.00532544 0.01155529 0.        ]
 [0.00605694 0.00808757 0.00833333]]
[[ 0.00787402  0.00026247 -0.        ]
 [ 0.00787402  0.01137358 -0.        ]
 [ 0.00656168  0.00577428  0.00833333]]


In [13]:
# Question 2
# Initialzing our matrices here
A = np.array([[52, 20, 25], [30, 50, 20],
             [18, 30, 55]])
B = np.array([4800,5800,5700])
# Factorizing LU
P, L, U = la.lu(A)
LU, piv = la.lu_factor(A)
# Solving the factorized system
X = la.lu_solve((LU, piv), B)
# Print the matrices
print(L)
print(U)
print(X)

[[1.         0.         0.        ]
 [0.57692308 1.         0.        ]
 [0.34615385 0.6        1.        ]]
[[52.         20.         25.        ]
 [ 0.         38.46153846  5.57692308]
 [ 0.          0.         43.        ]]
[40.05813953 71.31395349 51.62790698]


In [14]:
# Question 3
# Initialzing our matrices here
A = np.array([[40, -20, 0], [-20, 40, -20],
             [0, -20, 20]])
B = np.array([39.24, 58.88, 44.15])

# Factorizing LL
high.start_counters([events.PAPI_FP_OPS, ])
L = np.linalg.cholesky(A)
print(L)
print(np.transpose(L))
# Solving the factorized system
Y = la.solve(L, B)
print(Y)
X = la.solve(np.transpose(L), Y)
print(X)
x = high.stop_counters()
# Get floating point operations


[[ 6.32455532  0.          0.        ]
 [-3.16227766  5.47722558  0.        ]
 [ 0.         -3.65148372  2.5819889 ]]
[[ 6.32455532 -3.16227766  0.        ]
 [ 0.          5.47722558 -3.65148372]
 [ 0.          0.          2.5819889 ]]
[ 6.20438877 14.33207359 37.36783432]
[ 7.1135 12.265  14.4725]


In [ ]:
# Question 4
# Initialzing our matrices here, using from Q5
A = np.array([[-0.002, 4, 4], [-2, 2.906, -5.387],
             [3, -4.031, -3.112]])
B = np.array([7.998,-4.481,-4.143])
# Start timers
high.start_counters([events.PAPI_FP_OPS, ])
# Factorizing LU
P, L, U = la.lu(A)
LU, piv = la.lu_factor(A)
# Solving the factorized system
X = la.lu_solve((LU, piv), B)
x = high.stop_counters()
# Get floating point operations

In [18]:
# Question 5
# Initialzing our matrices here
A = np.array([[-0.002, 4, 4], [-2, 2.906, -5.387],
             [3, -4.031, -3.112]])
B = np.array([7.998,-4.481,-4.143])

# Solving the factorized system
X = la.solve(A, B)
print(X)
# Part B
A = np.array([[3, -4.031, -3.112], [-2, 2.906, -5.387],
             [-0.002, 4, 4]])
B = np.array([7.998,-4.481,-4.143])

# Solving the factorized system
X = la.solve(A, B)
print(X)
# Part C
A = np.array([[3, -4.031, -3.112], [-2, 2.906, -5.387],
             [-0.002, 4, 4]])
B = np.array([7.998,-4.481,-4.143])

# Solving the factorized system
X = la.solve(A, B)
print(X)

[1. 1. 1.]
[ 1.31815298 -0.89481838 -0.14027254]
[ 1.31815298 -0.89481838 -0.14027254]


In [16]:
# Question 6
# Initialzing our matrices here
A = np.array([[4, -1, -1, 0], [-1, 0.25, 0.25, -1],
             [4, 0, -1, -1], [0, -1, -1, 4]])
B = np.array([1,-1,2,0])
# Factorizing LU
P, L, U = la.lu(A)
LU, piv = la.lu_factor(A)
# Solving the factorized system
X = la.lu_solve((LU, piv), B)
print(X)

[1.   1.75 1.25 0.75]
