In [9]:
# Question 1

import sympy
import numpy as np
from copy import deepcopy
x = sympy.symbols('x')
y = sympy.symbols('y')
z = sympy.symbols('z')
X1 = 1/3 - 1/3*(-y + z)
Y1 = -1/6*(3*x + 2*z)
Z1 = 4/3 - 1/7*(3*x + 3*y)

values = {'X': 0, 'Y': 0, 'Z': 0}
previousvalues = {'X': 0, 'Y': 0, 'Z': 0}
currentvalue = []
while True:
    previousvalues['X'] = X1.subs([(y, values['Y']), (z, values['Z'])])
    currentvalue.clear()
    previousvalues['Y'] = Y1.subs([(z, values['Z']), (x, values['X'])])
    currentvalue.clear()
    previousvalues['Z'] = Z1.subs([(y, values['Y']), (x, values['X'])])
    currentvalue.clear()
    newvalues = {key: previousvalues[key] -
                 values.get(key, 0) for key in values}
    max = list(newvalues.values())
    print(max, np.max(max))
    values = deepcopy(previousvalues)
    if np.abs(np.max(np.abs(max))) <= 0.001:
        break
    print(previousvalues)

print("Jacoi Final Solution is: ", values)


values = {'X': 0, 'Y': 0, 'Z': 0}
previousvalues = {'X': 0, 'Y': 0, 'Z': 0}
currentvalue = []
while True:
    previousvalues['X'] = X1.subs(
        [(y, previousvalues['Y']), (z, previousvalues['Z'])])
    currentvalue.clear()
    previousvalues['Y'] = Y1.subs(
        [(z, previousvalues['Z']), (x, previousvalues['X'])])
    currentvalue.clear()
    previousvalues['Z'] = Z1.subs(
        [(y, previousvalues['Y']), (x, previousvalues['X'])])
    currentvalue.clear()
    newvalues = {key: previousvalues[key] -
                 values.get(key, 0) for key in values}
    max = list(newvalues.values())
    print(max, np.max(np.abs(max)))
    values = deepcopy(previousvalues)
    if np.abs(np.max(np.abs(max))) <= 0.001:
        break
    print(previousvalues)

print("Gauss Seidel Final Solution is: ", values)

W = 1.2
X1 = (1-1.2)*x + 1.2*(1/3 - 1/3*(-y + z))
Y1 = (1-1.2)*y + 1.2*(0 - 1/6*(3*x + 2*z))
Z1 = (1-1.2)*z + 1.2*(4/3 - 1/7*(3*x + 3*y))

values = {'X': 0, 'Y': 0, 'Z': 0}
previousvalues = {'X': 0, 'Y': 0, 'Z': 0}
currentvalue = []
while True:
    previousvalues['X'] = X1.subs(
        [(x, previousvalues['X']), (y, previousvalues['Y']), (z, previousvalues['Z'])])
    currentvalue.clear()
    previousvalues['Y'] = Y1.subs(
        [(z, previousvalues['Z']), (y, previousvalues['Y']), (x, previousvalues['X'])])
    currentvalue.clear()
    previousvalues['Z'] = Z1.subs(
        [(y, previousvalues['Y']), (z, previousvalues['Z']), (x, previousvalues['X'])])
    currentvalue.clear()
    newvalues = {key: previousvalues[key] -
                 values.get(key, 0) for key in values}
    max = list(newvalues.values())
    print(max, np.max(np.abs(max)))
    values = deepcopy(previousvalues)
    if np.abs(np.max(np.abs(max))) <= 0.001:
        break
    print(previousvalues)

print("SOR Final Solution is: ", values)


[0.333333333333333, 0, 1.33333333333333] 1.33333333333333
{'X': 0.333333333333333, 'Y': 0, 'Z': 1.33333333333333}
[-0.444444444444444, -0.611111111111111, -0.142857142857143] -0.142857142857143
{'X': -0.111111111111111, 'Y': -0.611111111111111, 'Z': 1.19047619047619}
[-0.156084656084656, 0.269841269841270, 0.452380952380952] 0.452380952380952
{'X': -0.267195767195767, 'Y': -0.341269841269841, 'Z': 1.64285714285714}
[-0.0608465608465609, -0.0727513227513227, -0.0487528344671202] -0.0487528344671202
{'X': -0.328042328042328, 'Y': -0.414021164021164, 'Z': 1.59410430839002}
[-0.00799949609473410, 0.0466742252456538, 0.0572562358276643] 0.0572562358276643
{'X': -0.336041824137062, 'Y': -0.367346938775510, 'Z': 1.65136054421769}
[-0.00352733686067014, -0.0150856638951877, -0.0165748839218227] -0.00352733686067014
{'X': -0.339569160997732, 'Y': -0.382432602670698, 'Z': 1.63478566029586}
[0.000496406675544958, 0.00728862973760924, 0.00797700032393900] 0.00797700032393900
{'X': -0.3390727543221

In [11]:
# Question 2
import sympy
import numpy as np
from copy import deepcopy
x = sympy.symbols('x')
y = sympy.symbols('y')
X1 = 59.2/0.03 - 1/0.03*(58.9*y)
Y1 = 47/6.1 - 1/6.10*(5.31*x)

values = {'X': 0, 'Y': 0}
previousvalues = {'X': 0, 'Y': 0}
currentvalue = []
n = 0
while n < 15:
    previousvalues['X'] = X1.subs(y, previousvalues['Y'])
    currentvalue.clear()
    previousvalues['Y'] = Y1.subs(x, previousvalues['X'])
    currentvalue.clear()

    newvalues = {key: previousvalues[key] -
                 values.get(key, 0) for key in values}
    max = list(newvalues.values())
    print(max, np.max(max))
    values = deepcopy(previousvalues)
    if np.max(np.abs(max)) <= 0.1:
        break
    print(previousvalues)
    n += 1
print("Final Solution is: ", values)


[0, 0] 0
Final Solution is:  {'X': 0, 'Y': 0}


In [2]:
from scipy.sparse.linalg import cg
import numpy as np

A = np.array([[1, 1/2, 1/3], [1/2, 1/3, 1/4], [1/3, 1/4, 1/5]])
B = np.array([5/6, 5/12, 17/60])

X = cg(A, B)
print(X)


(array([ 1., -1.,  1.]), 0)


In [1]:
# Question 4
import scipy.linalg as la
import numpy as np

mat = np.array([[-2, 1, 3], [1, 3, -1], [3, -1, 2]])
w, v = la.eig(mat)
print(mat)
print(w)
print(v)


[[-2  1  3]
 [ 1  3 -1]
 [ 3 -1  2]]
[-3.87298335+0.j  3.        +0.j  3.87298335+0.j]
[[ 0.8598926  -0.40824829  0.30646053]
 [-0.19382266 -0.81649658 -0.54384383]
 [-0.47224729 -0.40824829  0.78122713]]
